### ISSUE TITLE
Hibernate filter condition is incompatible with PostgreSQL

### ISSUE THREAD

**Issue by vahidpaz** [nanlabs/logical-delete#5]
The Hibernate filter condition which Logical Delete is using ("deleted = 0") is incompatible with PostgreSQL. Since the property is a Boolean PostgreSQL is not expecting the use of numbers, but a special boolean type.

For now I have changed the data type of "deleted" from Boolean to Byte, and I am successfully using H2 and Postgres I have not tested other engines such as Oracle yet.

**Comment by matiasgraziani** [comment]
When are you planing to make a new release with this fix?
